name: Translation Community Error Report
description: Report an error or suggest improvement for existing translation content
title: "🌐🔧 [LANGUAGE]: Brief description of the issue"
labels: ["translation", "bug", "correction", "community"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve the quality of our translations! 

        Translation quality is a community effort. Your feedback helps the translation community maintain and improve content for all users. Reports and suggestions are welcomed from anyone - whether you're a member of the translation community or a user of the translated content.

        **Community Approach:** Remember that translations are community-owned. This report will be shared with the translation community for that language, and multiple community members may collaborate on the resolution.

  - type: dropdown
    id: language
    attributes:
      label: Language
      description: Which language translation has the error?
      options:
        - English (en)
        - Farsi (fa)
        - Japanese (ja)
        - Spanish (es)
        - Other (please specify in description)
    validations:
      required: true

  - type: input
    id: page-url
    attributes:
      label: Page URL
      description: What page did you find the error on?
      placeholder: "https://kanbanguides.org/min/open-guide-to-kanban/"
    validations:
      required: true
  - type: dropdown
    id: error-type
    attributes:
      label: Type of Issue
      description: What kind of translation issue have you identified?
      options:
        - Incorrect translation/meaning
        - Grammar/syntax error
        - Spelling error
        - Missing translation
        - Formatting issue
        - Terminology inconsistency
        - Cultural adaptation needed
        - Other
    validations:
      required: true
  - type: textarea
    id: error-description
    attributes:
      label: Description of Issue
      description: Please describe the translation issue in detail. Include both what's currently there and what you think it should be.
      placeholder: "Current text: [paste current translation]\n\nIssue: [describe what's wrong]\n\nSuggested improvement: [your suggestion]"
    validations:
      required: true
  - type: textarea
    id: suggested-correction
    attributes:
      label: Suggested Improvement
      description: If you have suggestions for improvement, please provide them here. The translation community will review and collaborate on the best solution.
      placeholder: "Your suggested improvement or alternative translation..."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context that might help the translation community understand and address this issue
      placeholder: "Cultural context, regional considerations, or other helpful information..."
  - type: markdown
    attributes:
      value: |
        ---

        **Community Process:**
        - This report will be shared with the translation community for the specified language
        - The community will review and collaborate on the best resolution
        - Multiple community members may contribute to improving the translation
        - Resolution timeline depends on community availability and consensus

        Thank you for helping improve the quality of our community translations! 🌐✨
